---

coverage:
  status:
    patch:
      default:
        target: 90%
        threshold: 10%
    project:
      default:
        target: 90%
        threshold: 10%

ignore:
  - "internal/contextlocktest"