---
name: Release

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  renew-docs:
    name: Renew pkg.go.dev documentation
    runs-on: ubuntu-latest
    steps:
      - name: Pull released Go module version
        uses: andrewslotin/go-proxy-pull-action@master